AWSTemplateFormatVersion: '2010-09-09'
Description: window-post-api-lambdas

Transform:
- AWS::Serverless-2016-10-31

Resources:
  ###
  ### Roles
  ###

  # A role for the lambda
  LambdasExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole

  LambdasExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: WindowPostApiLambasExecutionPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Sub "${PostInputBucket.Arn}/*"
              - arn:aws:s3:::window-post-api-lambdas-postinputbucket-test/*
      Roles:
      - !Ref LambdasExecutionRole
      Groups:
      - !Ref LambdasExecutionGroup

  ###
  ### IAM groups
  ###

  # A group for users whom can assume the role
  LambdasExecutionGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: window-post-api-lambdas-execution

  ###
  ### Lambdas
  ###
  CreatePost:
    Type: AWS::Serverless::Function
    DependsOn: LambdasExecutionRole
    Properties:
      Handler: codes.rik.window.api.post.handler.CreatePostHandler
      Role: !GetAtt LambdasExecutionRole.Arn
      CodeUri: ../build/libs/post-api-lambdas-0.1-all.jar
      Timeout: 15
      MemorySize: 128
      Runtime: java8
      Environment:
        Variables:
          WINDOW_PostInputBucketArn: !GetAtt PostInputBucket.Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /create
            Method: post

  ###
  ### S3
  ###
  PostInputBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

